AddsSystem.Client/Controllers/ProfileController.cs
namespace AddsSystem.Client.Controllers
{
    using System;
    using System.Web.Mvc;
    using System.IO;
    using System.Linq;
    using System.Net.Mime;
    using Microsoft.AspNet.Identity;
    using AutoMapper.QueryableExtensions;
    using AddsSystem.Common.Constants;
    using AddsSystem.Services.Contracts;
    using AddsSystem.Models.ViewModels;
    using AddsSystem.Models.EntityModels;

    [Authorize]
    public class ProfileController : BaseController
    {
        private readonly IPostService postsData;

        public ProfileController(IPostService posts)
        {
            postsData = posts;
        } 

        public ActionResult Index()
        {
            string userid = User.Identity.GetUserId();
            var userPosts = postsData.UserAllPosts(userid); 
            return View(userPosts);
        }

        [OutputCache(CacheProfile = "ShortLived")]
        public ActionResult All()
        {
            var profilePosts = postsData.AllPosts().ProjectTo<AllProfilesVM>().OrderByDescending(c => c.UserPostId).ToList();
            return View(profilePosts); 
        }

        public ActionResult ContentById(int Id)
        {
            string userid = User.Identity.GetUserId();
            var content = postsData.ContentId(Id, userid).ProjectTo<ContentIdVM>().FirstOrDefault();
            return PartialView(Partials.UserAdId, content);
        }

        public ActionResult ContentId(int Id)
        {
            string MyUserId = User.Identity.GetUserId();
            ViewBag.MyUserId = MyUserId;
            var content = postsData.Content(Id).ProjectTo<AllProfilesVM>().FirstOrDefault();         
            return PartialView(Partials.ContentAdId, content);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserPost UserPost)
        {
            if (UserPost == null)
            {
                throw new ArgumentNullException("It's need all info about user post");
            }
            var filesRequest = Request;
            var server = Server;
            string userid = User.Identity.GetUserId();
            postsData.CreateUserPost(UserPost, userid, server, filesRequest);
            return RedirectToAction(Views.Index);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {          
            var userpost = postsData.EditById(id).ProjectTo<EditByIdVM>().FirstOrDefault();
            return View(userpost);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserPost userpost)
        {
            string userid = User.Identity.GetUserId();
            var filesRequest = Request;
            var server = Server;
            postsData.EditToPost(userpost, userid, server, filesRequest);
            return RedirectToAction(Views.Index);
        }

        public FileResult DownLoad(string p, string d)
        {
            return File(Path.Combine(Server.MapPath(Infrastructure.FolderPath), p), MediaTypeNames.Application.Octet, d);
        }

        [HttpPost]
        public JsonResult DeleteFile(string id)
        {
            var server = Server;         
            return postsData.DeleteFileByStringId(id, server);
        }

        [Authorize]
        public ActionResult Delete(int id)  
        {
            var server = Server;
            postsData.Delete(id, server);
            return RedirectToAction(Views.Index);
        }
    }
}

AddsSystem.Client/Views/Shared/_AddResult.cshtml
@model AddsSystem.Models.ViewModels.AllProfilesVM

<div style="background-color:#e6f2ff;">
    <div class="Add">
        <div>
            <strong>
                @Model.UserPostId
            </strong>

        </div>
        <div>
            <strong>
                @Model.Title
            </strong>
        </div>
        <div>
            <strong>
                @Model.Info
            </strong>
        </div>
    </div>
    <br />
    <table class="Add">
        <tr>
            @foreach (var p in Model.PostImages)
            {
                <td>
                    <img src="/Profile/DownLoad/?p=@(p.Id + p.Extension)&d=@p.FileName" width="185" height="120">
                </td>
            }
            @{
                string verify = Model.UserId == @ViewBag.MyUserId ? "visible" : "hidden";
            }

                <td class="@verify">
                    @Html.ActionLink("Edit", "Edit", "Profile", new { id = Model.UserPostId }, null) 
                </td>
                <td class="@verify">
                    @Html.ActionLink("Delete", "Delete", "Profile", new { id = Model.UserPostId }, null)
                </td>
</tr>
    </table>
    <br />
</div>
    @section scripts {
        @Scripts.Render("~/bundles/jqueryajax")
    }

AddsSystem.Client/Views/Shared/_AddsResult.cshtml
@model AddsSystem.Models.ViewModels.ContentIdVM
    <div class="Add">
        <div>
            <strong>
                @Model.UserPostId
            </strong>
        </div>
        <div>
            <strong>
                @Model.Title
            </strong>
        </div>
        <div>
            <strong>
                @Model.Info
            </strong>
        </div>
    </div>
    <br />
    <table class="Add">
        <tr>
            @foreach (var p in Model.PostImages)
            {
                <td>
                    <img src="/Profile/DownLoad/?p=@(p.Id + p.Extension)&d=@p.FileName" width="150" height="85">
                </td>
            }
            <td>
                @Html.ActionLink("Edit", "Edit", "Profile", new { id = Model.UserPostId }, null) 
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Profile", new { id = Model.UserPostId }, null)
            </td>
        </tr>
    </table>
    <br />



@section scripts {
    @Scripts.Render("~/bundles/jqueryajax")
}

AddsSystem.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adds System - ASP.NET MVC App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery") 
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AddsSystem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("All", "All", "Profile")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                    <li>@Html.ActionLink("Create new add", "Create", "Profile")</li>
                    <li><a href="chat.html" target="_blank">Chat</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()

        <br />
        <br />
        <br />
        <br />
        <hr />

        <footer>
            <h5>ASP.NET MVC with Entity Framework - Code First</h5>
            <h6>Repository Pattern(T), Dependancy Injection (Inversion of Control container) with Ninject, Unit of Work, AutoMapper, SignalR Chat</h6> <br/>
            <p>&copy; Sekul Kamberov 2017</p>

        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>